Repository octokit/auth-oauth-app.js, pull requests merged in 2021-05, with the labels that each got.

#180 feat: set basic auth from client ID/secret to bump rate limit
  src/hook.ts
  src/index.ts
  src/types.ts
  test/index.test.ts
Labels: bug

#183 feat(typescript): export `FactoryGitHubWebFlow`, `FactoryGitHubDeviceFlow`
  src/index.ts
Labels: bug, typescript

#184 ci: fix branch name for "Update Prettier" workflow
  .github/workflows/update-prettier.yml
  package.json
Labels: maintenance
