Repository octokit/auth-oauth-app.js, pull requests merged in 2022-07, with the labels that each got.

#244 fix: revert dependency update of `@octokit/request`
  package-lock.json
  package.json
Labels: bug

#237 ci: stop testing against NodeJS v10, v12
  .github/workflows/test.yml
  package.json
Labels: blocked, maintenance

#247 ci(test): use test_matrix and test jobs
  .github/workflows/test.yml
Labels: maintenance

#251 tests: remove `state` parameter for Oauth web flow
  test/index.test.ts
Labels: maintenance

#253 [deps] updates pika/pack to a non vulnerable version
  package-lock.json
  package.json
Labels: dependencies, maintenance
