Repository octokit/auth-oauth-app.js, pull requests merged in 2023-06, with the labels that each got.

#342 fix(build): switch to esbuild
  package-lock.json
  package.json
  scripts/build.mjs
  src/auth.ts
  src/hook.ts
  src/index.ts
  src/types.ts
  test/tsconfig.test.json
  tsconfig.json
Labels: Type: Maintenance

#337 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package.json
  scripts/build.mjs
Labels: Type: Maintenance, Type: Breaking change

#349 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation
